name: First GitHub action test

on:
  push:

jobs:
  b17_first_job:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Message
        run: echo "Welcome to GitHub Actions by BATCH17D CHAMPS"
